# High-level config
ankifier_config:
  mongodb_name: ankifier # Mongo database - same as for `import_data.sh`
  deepl_api_key: 2914650b-963b-4e66-92d2-7f6a1a39f703:fx # Your DeepL API key

# One config for each language you want to generate cards for. 
language_configs:
  german:
    anki_deck: Languages::German
    card_type: Basic
    wiktionary_collection: de_wiktionary
    spacy_model: de_core_news_md
    word_settings: /Users/enesihsa/Desktop/University/Proj/ankifier/settings/language_configs/german.yaml
  russian: # Should match what you pass as --language argument
    anki_deck: Languages::Russian # Anki deck with the cards for this language
    card_type: Russian # Anki card type to use for importing cards
    wiktionary_collection: ru_wiktionary # The collection where you've saved a Wiktionary export using `import_data.sh`.
    spacy_model: ru_core_news_sm # SpaCy model for this language (https://spacy.io/models)
    word_settings: /Users/enesihsa/Desktop/University/Proj/ankifier/settings/language_configs/russian.yaml # Absolute path to the YAML file which defines how Wiktionary entries are converted to cards (in json)  
  